[package]
name = "purescript_waterslide_codegen"
version = "0.1.0"
authors = ["Tom Houlé <tom@tomhoule.com>"]

[dependencies]
purescript_waterslide = { path = "../purescript_waterslide" }
proc-macro2 = "*"
quote = "*"
syn = "*"

[lib]
proc-macro = true
