[package]
name = "purescript_waterslide_tests"
version = "0.1.0"
authors = ["Tom Houlé <tom@tomhoule.com>"]

[dependencies]
purescript_waterslide = { path = "../purescript_waterslide" }
purescript_waterslide_derive = { path = "../purescript_waterslide_derive" }
void = "*"
